# Pandas Exercise

#### Import pandas as pd.

In [1]:
import pandas as pd

#### Read Salaries.csv as a dataframe called sal.

In [2]:
sal=pd.read_csv('Salaries.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'Salaries.csv'

#### Check the head of the DataFrame.

In [ ]:
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

#### Use the .info() method to find out how many entries there are.

In [ ]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
Index: 148654 entries, 1 to 148654
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   EmployeeName      148654 non-null  object
 1   JobTitle          148654 non-null  object
 2   BasePay           148045 non-null  float64
 3   OvertimePay       148650 non-null  float64
 4   OtherPay          148650 non-null  float64
 5   Benefits          112491 non-null  float64
 6   TotalPay          148654 non-null  float64
 7   TotalPayBenefits  148654 non-null  float64
 8   Year              148654 non-null  int64
 9   Notes             0 non-null       float64
 10  Agency            148654 non-null  object
 11  Status            0 non-null       float64
dtypes: float64(8), int64(1), object(3)
memory usage: 14.7+ MB

**What is the average BasePay ?**

In [ ]:
sal['BasePay'].mean()

np.float64(66325.4488404877)

#### What is the highest amount of OvertimePay in the dataset ?

In [ ]:
sal['OvertimePay'].max()

np.float64(245131.88)

#### What is the job title of  JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll).

In [ ]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle'].values[0] 
# since we are only interested in the value itself not its type as an object we added .values[0]

'CAPTAIN, FIRE SUPPRESSION'

#### How much does JOSEPH DRISCOLL make (including benefits)?

In [ ]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['TotalPayBenefits'].values[0]

np.float64(270324.91)

#### What is the name of highest paid person (including benefits)?

In [ ]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].max()]['EmployeeName'].values[0]

'NATHANIEL FORD'

#### What is the name of lowest paid person (including benefits)? Do you notice something strange about how much he or she is paid?

In [ ]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].min()]['EmployeeName'].values[0]
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].min()]
#Yes, the total pay benefits are negative.

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

#### What was the average (mean) BasePay of all employees per year? (2011-2014) ?

In [ ]:
sal.groupby('Year')['BasePay'].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

#### How many unique job titles are there?

In [ ]:
sal['JobTitle'].nunique()

2159

#### What are the top 5 most common jobs?

In [ ]:
sal['JobTitle'].value_counts().head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

#### How many Job Titles were represented by only one person in 2013? (e.g. Job Titles with only one occurence in 2013?)

In [ ]:
in_2013=sal[sal['Year'] == 2013]
count_2013=in_2013['JobTitle'].value_counts()==1
int(count_2013.sum())

202

Malak Moustafa Abdel Maboud Salem    20237015 s1

Jumanah Muhammad Ali Rushdi s1

# Great Job!